export const data = [
    {
        "title": "Day tour",
        "type": "nature",
        "image": "https://i.ibb.co/2qGZvzt/tajmahal.jpg",
        "isVideo": false,
        "images": {
            "image1": "https://i.ibb.co/RQPRc20/tajmahal3.jpg",
            "image2": "https://i.ibb.co/G3N0pwf/tajmahal1.jpg",
            "image3": "https://i.ibb.co/tpGC51S/tajmahal2.webp"
        },
        "description": "Tajmahal: This is a longer card with supporting text below",
        "page_description": "this is page description",
        "duration": "1 Hour",
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        "time": "10-12 hours"
    },
    {
        type: 'nature',
        title: 'Guided tour',
        image: 'https://i.ibb.co/TkStjkC/Qutubminar.jpg',
        isVideo: false,
        images: {
            image1: 'https://i.ibb.co/BydJsRY/qutub1.jp',
            image2: 'https://i.ibb.co/C2cyXt2/qutub.jpg',
            image3: 'https://i.ibb.co/4f3FV5M/lodhigarden.jpg',
        },
        description: 'Delhi city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '2 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',
    },
    {
        type: 'nature',
        title: 'Guided tour',
        isVideo: false,
        image: 'https://i.ibb.co/ZhG0gYY/redfort.jpg',
        images: {
            image1: 'https://i.ibb.co/8YH2k0v/Red-Fortog.webp',
            image2: 'https://i.ibb.co/5Bg87Nz/redfort2.webp',
            image2: 'https://i.ibb.co/DLk2b7z/snowmasti.jpg',
        },
        description: 'Delhi city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '1 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',

    },
    {
        type: 'nature',
        title: 'Guided tour',
        isVideo: false,
        image: 'https://i.ibb.co/4wqmFCN/indiagate3.webp',
        images: {
            image1: 'https://i.ibb.co/4wqmFCN/indiagate3.webp',
            image2: 'https://i.ibb.co/b2DQ4HK/india3.jpg',
            image3: 'https://i.ibb.co/q1XqHH8/India2.webp',
        },
        description: 'Delhi city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '1 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',
    },
    {
        type: 'food',
        title: 'Guided tour',
        isVideo: false,
        image: 'https://i.ibb.co/gDwgVKk/hotel2.webp',
        images: {
            image1: 'https://i.ibb.co/3NBY3p3/hotel7.webp',
            image2: 'https://i.ibb.co/NmTNb4N/oden.web',
            image3: 'https://i.ibb.co/M87SMZZ/Food6-1.webp',
        },
        description: 'Guugram city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '1 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',
    },
    {
        type: 'food',
        title: 'Guided tour',
        image: 'https://i.ibb.co/M87SMZZ/Food6-1.webp',
        isVideo: false,
        images: {
            image1: 'https://i.ibb.co/Gth74NX/Food6.webp',
            image2: 'https://i.ibb.co/8r8vCMr/Food1-1.jpg" a',
            image3: 'https://i.ibb.co/BLXCMH7/ad2.webp',
        },
        description: 'Guugram city: This is a longer card with supporting text below',
        duration: '1 Hour',
        page_description: "this is page description",
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',
    },
    {
        type: 'food',
        title: 'Guided tour',
        isVideo: false,
        image: 'https://i.ibb.co/2MFSd4H/Food5.web',
        images: {
            image1: 'https://i.ibb.co/3NBY3p3/hotel7.webp',
            image2: 'https://i.ibb.co/NmTNb4N/oden.web',
            image3: 'https://i.ibb.co/M87SMZZ/Food6-1.webp',
        },
        description: 'Guugram city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '1 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',


    },
    {
        type: 'food',
        title: 'Guided tour',
        isVideo: false,
        image: 'https://i.ibb.co/JmGKBZf/Food8.jpg',
        images: {
            image1: 'https://i.ibb.co/3NBY3p3/hotel7.webp',
            image2: 'https://i.ibb.co/NmTNb4N/oden.web',
            image3: 'https://i.ibb.co/M87SMZZ/Food6-1.webp',
        },
        description: 'Guugram city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '1 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',
    },
    {
        type: 'culture',
        title: 'Jaynti park',
        isVideo: false,
        image: 'https://i.ibb.co/ckTRBN4/buddha-jayanti-park1-1.jpg',
        images: {
            image1: 'https://i.ibb.co/tqrXBj2/central-park1-1.jpg',
            image2: 'https://i.ibb.co/NmTNb4N/oden.web',
            image3: 'https://i.ibb.co/M87SMZZ/Food6-1.webp',
        },
        description: 'Guugram city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '1 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',
    },
    {
        type: 'culture',
        title: 'Guided tour',
        isVideo: false,
        image: 'https://i.ibb.co/xM3J0xY/park.jpg',
        images: {
            image1: 'https://i.ibb.co/tqrXBj2/central-park1-1.jpg',
            image2: 'https://i.ibb.co/NmTNb4N/oden.web',
            image3: 'https://i.ibb.co/k0Qz01D/deer-park1-1.jpg',
        },
        description: 'Guugram city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '1 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',
    },
    {
        type: 'culture',
        title: 'Guided tour',
        isVideo: false,
        image: 'https://i.ibb.co/k0Qz01D/deer-park1-1.jpg',
        images: {
            image1: 'https://i.ibb.co/tqrXBj2/central-park1-1.jpg',
            image2: 'https://i.ibb.co/NmTNb4N/oden.web',
            image3: 'https://i.ibb.co/k0Qz01D/deer-park1-1.jp',
        },
        description: 'Guugram city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '1 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',

    },
    {
        type: 'culture',
        title: 'Guided tour',
        isVideo: false,
        image: 'https://i.ibb.co/xM3J0xY/park.jpg',
        images: {
            image1: 'https://i.ibb.co/tqrXBj2/central-park1-1.jpg',
            image2: 'https://i.ibb.co/RcX6Wqb/garden.jpg',
            image3: 'https://i.ibb.co/k0Qz01D/deer-park1-1.jp',
        },
        description: 'Guugram city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '1 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',
    },
    {
        type: 'activities',
        title: 'Guided tour',
        isVideo: false,
        image: 'https://i.ibb.co/ZNHz9Sz/vrindavan.jpg',
        images: {
            image1: 'https://i.ibb.co/svLJdGB/varanasi.jpg',
            image2: 'https://i.ibb.co/NmTNb4N/oden.web',
            image3: 'https://i.ibb.co/k0Qz01D/deer-park1-1.jp',
        },
        description: 'Guugram city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '1 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',
    },
    {
        type: 'activities',
        title: 'Guided tour',
        isVideo: false,
        image: 'https://i.ibb.co/Mfwc3tz/cover.png',
        images: {
            image1: 'https://i.ibb.co/svLJdGB/varanasi.jpg',
            image2: 'https://i.ibb.co/NmTNb4N/oden.web',
            image3: 'https://i.ibb.co/k0Qz01D/deer-park1-1.jp',
        },
        description: 'Guugram city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '1 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',
    },
    {
        type: 'activities',
        title: 'Guided tour',
        isVideo: false,
        image: 'https://i.ibb.co/rd9FJ2s/N4-1.jpg',
        images: {
            image1: 'https://i.ibb.co/svLJdGB/varanasi.jpg',
            image2: 'https://i.ibb.co/NmTNb4N/oden.web',
            image3: 'https://i.ibb.co/k0Qz01D/deer-park1-1.jp',
        },
        description: 'Guugram city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '1 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',
    },
    {
        type: 'activities',
        title: 'Guided tour',
        isVideo: false,
        image: 'https://i.ibb.co/QY7Fsf4/manali.jpg',
        images: {
            image1: 'https://i.ibb.co/T1m7mvQ/ad3-1.jpg',
            image2: 'https://i.ibb.co/rd9FJ2s/N4-1.jpg',
            image3: 'https://i.ibb.co/k0Qz01D/deer-park1-1.jp',
        },
        description: 'Guugram city: This is a longer card with supporting text below',
        page_description: "this is page description",
        duration: '1 Hour',
        "discount": 2842,
        "price": 3250,
        "review_count": 232,
        time: '3-4 hours',
    },
]